c_library('demo',
  sources = [
    'input.cc',
    'runner.cc',
  ],
  deps = [
    '//etl/stm32f4xx',
  ],
)

c_library('terminal',
  sources = [
    'terminal.cc',
  ],
  deps = [
    '//etl/stm32f4xx',
    '//vga',
  ],
)
