depth := ..
products := demo stuff

demo[type] := library

demo[cc_files] := input.cc

demo[cc_flags] := -std=gnu++0x

demo[libs] := \
  etl/stm32f4xx:stm32f4xx

stuff[type] := subdirectories

include $(depth)/build/Makefile.rules
